### ISSUE TITLE
jobe-created accounts automatically deleted by central management system such as puppet

### ISSUE THREAD

**Issue by kcleung** [trampgeek/jobe#12]
I have just tried to install jobe into a VM that is centrally managed using puppet by our ITS.  However, the accounts created by jobe were deleted by puppet, because these automatically-created accounts.  

To solve this problem, I have added the argument '-r' in useradd called by the installer script "install" to  make all jobe users as system users, thus will not be touched by central management systems.

I will create a pull request that will fix this issue.

**Comment by trampgeek** [comment]
Thanks Kai Cheung
