### ISSUE TITLE
web server unable to access contents of /var/www/html/jobe/ and therefore can't run

### ISSUE THREAD

**Issue by kcleung** [trampgeek/jobe#14]
I cloned jobe onto /var/www/html, changed into /var/www/html/jobe, and run:

sudo ./install

./install only changed ownership of the directory "files" to jobe:www-data (files needs to be written by jobe), but the rest of the contents are still root:root, with access of directories such as application, nbproject, runguard and system remain as rwxr-xr--

As a result, the web server cannot read the directories application, nbproject and runguard, and therefore cannot run jobs.

Therefore should install change group ownership of all contents to www-data, to ensure www-data can read the necessary files?  Or should install make everything world-readable and all directories world-executable?

**Comment by trampgeek** [comment]
It looks like root's umask is set to 023 rather than 022, which is the Ubuntu default. Can you confirm that, please? What version of Linux are you using? Did you change the default umask, or is 023 the default value for that flavour of Linux?

Thanks for reporting.

Richard

**Comment by kcleung** [comment]
I am using Ubuntu 16.04.  This is the command I used to check out jobe:

$ cd /var/www/html
$ sudo git clone https://github.com/trampgeek/jobe
$ cd jobe
$ sudo ./install

The system says the root umask is 0077:

$ sudo su
$ umask
0077
$


Therefore should our install script assume nothing, and set permission and ownership of everything within jobe to correct values?

**Comment by trampgeek** [comment]
That's odd. All my Ubuntu 16.04 systems say root's umask is 022. However, you've identified a dependence on the umask that should be eliminated, anyway. So I've modified the install script to give the web server read access to all files, and pushed it to github.

Thanks for drawing my attention to it.

Richard
