### ISSUE TITLE
Limit reached

### ISSUE THREAD

**Issue by yakarsu** [trampgeek/jobe#32]
Hello

I saw error bellow yesterday. What would you recommend?

"Failed to run tests
Sandbox submission limit reached"

**Comment by trampgeek** [comment]
I assume this happened while you were using jobe2.cosc.canterbury.ac.nz? As far as I know, it can't happen on any other jobe server. It occurs fairly regularly when users abuse the service offered by jobe2. The whole world gets locked out for an hour or so.

You do realise, I hope, that the jobe2.cosc.canterbury.ac.nz server is available only for brief testing, and is not a production server? You should install your own server as soon as you have decided to make continued use of CodeRunner. Please see the CodeRunner installation instructions [here](https://github.com/trampgeek/moodle-qtype_coderunner#installing-coderunner-from-scratch) and [here](https://github.com/trampgeek/moodle-qtype_coderunner#sandbox-configuration).

**Comment by yakarsu** [comment]
Thank you richard I didn't know you were a test server. I will install my own server Can i install only jobe server? I installed coderunner plugin on moodle before

**Comment by trampgeek** [comment]
I'm not sure what you mean by "can I install only Jobe server?". I suggest you read the Jobe install instructions and decide if you want to use the JobeInABox docker image or a conventional Linux + Jobe server.

**Comment by yakarsu** [comment]
Thanks richard i did install jobe server
