### ISSUE TITLE
octave wants many xserver and gnome dependencies on Ubuntu 20.04

### ISSUE THREAD

**Issue by dave559** [trampgeek/jobe#33]
I'm trying to build a new Jobe server (for testing) on Ubuntu 20.04.

`octave` now seems to want many `xserver` and `gnome` dependencies (which I don't think it did by default previously?).

Do you know if there is a way to install a more minimal non-gui version of Octave, as it seems unnecessary (and undesirable) to bring in the whole windowing system when it is only going to be used programmatically on an otherwise 'headless' server? Possibly it might be worth liaising with the Ubuntu octave packagers about this?

**Comment by dave559** [comment]
From asking elsewhere about trying to avoid X dependencies for another package, it turns out that the following will install `octave` without bringing in the X window system.

```
# Install the No-X version of gnuplot explicitly first (if you need gnuplot)
sudo apt install gnuplot-nox

sudo apt-get install --no-install-suggests --no-install-recommends  octave
```

**Comment by trampgeek** [comment]
Thanks Dave. I've modified the octave install instructions in Jobe's readme.md to match your suggestion.
