### ISSUE TITLE
How to support the SQL?

### ISSUE THREAD

**Issue by sunyongke** [trampgeek/jobe#41]
This is a best sandbox server. I already used these application.
and I want to know how to enable the SQL support?

**Comment by trampgeek** [comment]
The Jobe installer builds a system with sqlite3. The CodeRunner _sql_ question type uses this via Python3.  If you're using Jobe outside of CodeRunner you'll have to write your own glue code in Python (or other language of your choice) to set up an sqlite3 database file and run sql commands on it.

Here's the template for the CodeRunner question type as a text file: [sqltemplate.txt](https://github.com/trampgeek/jobe/files/5585588/sqltemplate.txt). If you have further questions related to CodeRunner, please ask them on the [CodeRunner question authors forum](https://coderunner.org.nz/mod/forum/view.php?id=51) .

If you're looking for sql support beyond the level of sqlite3, I'm afraid you're out of luck.

**Comment by sunyongke** [comment]
Thanks for your template
