### ISSUE TITLE
How to send multiple inputs on API request

### ISSUE THREAD

**Issue by tavivek** [trampgeek/jobe#44]
Hi Team, 

Is it possible to send one or more test cases/input in the same API request?
Right now, I have to send the input one by one to JobeServer.

Thanks

**Comment by trampgeek** [comment]
Jobe does what is says on the box - runs a single job, with its standard input and possible support files. There can only be one standard input for a single run, so the short answer is no. But there's nothing stopping you from submitting a job which is essentially a script defining multiple test cases and associated standard inputs. The script can run the (embedded) program for each test, switching the standard input between tests. We do this routinely when using Jobe from CodeRunner. Yet another approach is to upload a zip file of runs and have the script/program unzip that file and run all the jobs in it.
