### ISSUE TITLE
Security problem with Jobe

### ISSUE THREAD

**Issue by thopd88** [trampgeek/jobe#50]
Language selected: Python3
source code:
```
a = eval(input())
print(a)
```

payload:
`__import__('os').popen('ls /').read()`

This will show up root directory

**Comment by trampgeek** [comment]
This is not a security flaw. Jobs running on the Jobe server have roughly the same rights as any non-privileged user would have who is logged on to the server, except that they have no home directory and have limits on their use of CPU time, memory and disk output. Read-only access to the root directory isn't a problem.
