### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by colenot** [trampgeek/jobe#52]
As PHP7.4 is becoming unsupported later this year, can Jobe be updated to work with php8 ?

Here is the error we get for each call (including testsubmit.py) : 

<p>Message:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated</p>
<p>Filename: libraries/REST_Controller.php</p>
<p>Line Number: 1050</p>

**Comment by trampgeek** [comment]
Thanks for reporting. I just pushed an update. Sorry about the delay in fixing but I didn't have a PHP8 system at the time and was busy with teaching.
