### ISSUE TITLE
testsubmit "Memory limit exceeded in C (seg faults)"

### ISSUE THREAD

**Issue by jpschneiders** [trampgeek/jobe#53]
Hi,

I have updated Jobe to version 1.6.6 on an up to date Debian 10 server. When I launch ` python3 ./testsubmit.py` to test the install the test "Memory limit exceeded in C (seg faults)" fails since the requested `malloc` call succeeds. After investigating it seems to me that the new default memory limit for C tasks is 500MB. If I edit `testsubmit.py` and change the `#define CHUNKSIZE 500000000` line to for example `#define CHUNKSIZE 550000000` the malloc fails as expected and the test succeeds. It would be nice if you could patch the code accordingly.

Best regards,
Jean-Pierre

**Comment by trampgeek** [comment]
Thanks for reporting. I just pushed an update (with a 2GB malloc for future proofing).
