### ISSUE TITLE
README doesn't reflect latest versions?

### ISSUE THREAD

**Issue by gigamonkey** [trampgeek/jobe#78]
Hi, after a very successful year using Jobe for my Java classes at Berkeley High School last year (thank you!) I'm updating things for next year. Since I have my own fork I'm looking at the branches in this repo and trying to figure out what the latest and greatest is.

The README lists version 1.8.0 but I see tags for 1.9 and 2.0 an also the JobeV1 and JobeV2 branches. Which one should I try to merge into my fork if I want the latest stable version?

Perhaps the change log in the readme should be updated for all the existing versions, even if just to warn people off any of the ones that maybe aren't ready for prime time yet?

Cheers!

**Comment by trampgeek** [comment]
Hi Peter
Thanks for the reminder. I did a major rewrite of Jobe over our Southern Hemisphere Christmas break, calling in JobeV2. I wanted to run it here for a bit before making it the master branch, but teaching a class of nearly 1000 students meant that "a bit" expanded out to "a full semester". But the semester has now finished, and I've just merged the V2 branch back into Master and pushed to github.

Let me know if there are any further confusions or problems.

Richard
