### ISSUE TITLE
Adding password protection to Jobe server prevents connection with Moodle

### ISSUE THREAD

**Issue by dragos5436** [trampgeek/jobe#79]
Hi there,

We've recently set up a Jobe server for our institution following your instructions from the jobeinabox repo. The server works, it is able to receive and execute requests from Moodle. However, after adding password protection to the Jobe server so that it's not open to the public, we get a "Sandbox submission limit reached" error when trying to execute code within the coderunner plugin:
![image](https://github.com/user-attachments/assets/2159a2e6-7229-4e7e-b5c8-29a8de9a89d7)

The way we set this up was by first creating a .htpasswd password file on the server and then adding this block of code to the <VirtualHost *:443> of the 000-jobe.conf file:

"    <Location />
     AuthName "Dialog prompt"
     AuthType Basic
     AuthUserFile /var/www/html/.htpasswd
     Require valid-user
   </Location>
"
Is there any setting in Moodle where we could allow outgoing requests to bypass the authentication?

Thank you.

**Comment by trampgeek** [comment]
The usual way to control access to a Jobe server is via the firewall: see https://github.com/trampgeek/jobe?tab=readme-ov-file#securing-the-site. I recommend that approach, unless there's some reason it won't work for you?

**Comment by dragos5436** [comment]
Hi,

Thanks for the tip, we'll try to use the recommended approach. Will re-open this if we run into any other issues.
