### ISSUE TITLE
Trying to run Haskell inside a jobe server

### ISSUE THREAD

**Issue by SSIvanov19** [trampgeek/jobe#83]
Hello,
I am trying to run a Haskell program inside Jobe server, using JS. Here is my script:
```js
const { exec, execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const stream = require('stream');

fs.writeFileSync("prog.hs", `
{{ STUDENT_ANSWER | e('c') }}
`); 

try {
        let res = execSync(`runghc ${cflags} prog.hs`, { env: process.env, stdio: 'inherit' });
        
        if (res !== null){
            console.log(res.toString('utf8'));
        }
} catch (error){
        console.log(error.message);
}
```
When I run it on the server using node, the script runs without a problem. But when I submitted it through code runner on Moodle, I get the following error:
```
Command failed: runghc  prog.hs
ghc: failed to create OS thread: Cannot allocate memory
```
The server I run it is a VM running:
- Ubuntu 24.04
- Using latest version of Jobe (2.0.2)
- 32 Cores
- 16 GB of RAM

**Comment by SSIvanov19** [comment]
I’ve successfully run the program through Code Runner after increasing the memory limit. Now, I’m trying to achieve the same result using Scratchpad, but I can’t find where to adjust the memory limit in Scratchpad. Do you have any ideas on how to do this?

**Comment by trampgeek** [comment]
Enter the following into the UI Parameters field:

{"params": {"memorylimit": 0}}
